import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Check, Dumbbell, LogOut, Plus, Ruler, Save, Scale, ShieldCheck, Sparkles, Trash2 } from 'lucide-react';
import { supabase } from './supabase';
import './styles.css';

const today=()=>new Date().toISOString().slice(0,10);
const starterWorkout=[
 {id:1,name:'90–90 Breathing',prescription:'2 × 5 breaths',category:'PREP',sets:[false,false],reps:[5,5]},
 {id:2,name:'Glute Bridge',prescription:'2 × 10 · 3s hold',category:'PREP',sets:[false,false],reps:[10,10]},
 {id:3,name:'Dead Bug',prescription:'2 × 6 / side',category:'PREP',sets:[false,false],reps:[6,6]},
 {id:4,name:'Tempo Push-up',prescription:'3 × 8–12',category:'PUSH',sets:[false,false,false],reps:[10,10,10]},
 {id:5,name:'Reverse Snow Angel',prescription:'3 × 10–15',category:'PULL',sets:[false,false,false],reps:[12,12,12]},
 {id:6,name:'Bulgarian Split Squat',prescription:'3 × 8 / side',category:'LEGS',sets:[false,false,false],reps:[8,8,8]},
 {id:7,name:'Hollow Body Hold',prescription:'3 × 20 sec',category:'CORE',sets:[false,false,false],reps:[20,20,20]}
];
const starterSkills=[
 {name:'Handstand',icon:'HS',level:2,progress:46,next:'Wall shoulder taps',stages:['Pike hold','Wall handstand','Wall shoulder taps','Freestanding'],accent:'#f4ff5b'},
 {name:'L-sit',icon:'LS',level:2,progress:58,next:'One-leg L-sit',stages:['Support hold','Tuck L-sit','One-leg L-sit','Full L-sit'],accent:'#7c6cff'},
 {name:'Planche',icon:'PL',level:1,progress:24,next:'Tuck planche',stages:['Planche lean','Tuck planche','Advanced tuck','Straddle'],accent:'#ff7a45'},
 {name:'Pistol squat',icon:'PS',level:2,progress:67,next:'Counterweight pistol',stages:['Box pistol','Assisted pistol','Counterweight','Full pistol'],accent:'#33d49d'}
];
function Auth(){const [mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''); const go=async(e)=>{e.preventDefault();setMsg('');const fn=mode==='signup'?supabase.auth.signUp({email,password,options:{emailRedirectTo:location.href.split('#')[0]}}):supabase.auth.signInWithPassword({email,password});const {data,error}=await fn;if(error)setMsg(error.message);else if(mode==='signup'&&!data.session)setMsg('Check your email to confirm your account.');};return <div className="content"><main><section className="hero card"><div className="hero-copy"><span className="pill lime">FORM CLOUD</span><h2>Your training.<br/>On every device.</h2><p>Private Supabase account + Row Level Security.</p></div></section><form className="card measurement-form" onSubmit={go}><span className="eyebrow">{mode==='signup'?'CREATE ACCOUNT':'SIGN IN'}</span><h2>{mode==='signup'?'Start syncing':'Welcome back'}</h2><div className="inputs"><label>Email<div><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div></label><label>Password<div><input type="password" minLength="6" required value={password} onChange={e=>setPassword(e.target.value)}/></div></label></div><button className="primary" type="submit"><ShieldCheck size={18}/>{mode==='signup'?'Create account':'Sign in'}</button>{msg&&<p>{msg}</p>}<button type="button" className="link" onClick={()=>setMode(mode==='signup'?'signin':'signup')}>{mode==='signup'?'Already have an account? Sign in':'New here? Create an account'}</button></form></main></div>}
function App(){const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('workout'),[workout,setWorkout]=useState(starterWorkout),[skills,setSkills]=useState(starterSkills),[measurements,setMeasurements]=useState([]),[history,setHistory]=useState([]),[status,setStatus]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session?.user?.id]);
 const load=async()=>{setStatus('Syncing…');const uid=session.user.id;const [wp,sp,ms,hs]=await Promise.all([supabase.from('workout_plans').select('*').eq('name','Full Body A').maybeSingle(),supabase.from('skill_progress').select('*').order('name'),supabase.from('measurements').select('*').order('measured_on'),supabase.from('workout_sessions').select('*').order('session_date')]);if(wp.error||sp.error||ms.error||hs.error){setStatus('Sync error');return} if(wp.data)setWorkout(wp.data.exercises);else await supabase.from('workout_plans').insert({user_id:uid,name:'Full Body A',exercises:starterWorkout});if(sp.data.length)setSkills(sp.data.map(x=>({name:x.name,icon:x.icon,level:x.level,progress:x.progress,next:x.next_step,stages:x.stages,accent:x.accent})));else await supabase.from('skill_progress').insert(starterSkills.map(x=>({user_id:uid,name:x.name,icon:x.icon,level:x.level,progress:x.progress,next_step:x.next,stages:x.stages,accent:x.accent})));setMeasurements(ms.data.map(x=>({id:x.id,date:x.measured_on,weight:x.weight_lb==null?'':Number(x.weight_lb),waist:x.waist_cm==null?'':Number(x.waist_cm)})));setHistory(hs.data);setStatus('Synced')};
 const saveWorkout=async(next=workout)=>{setWorkout(next);setStatus('Saving…');const {error}=await supabase.from('workout_plans').upsert({user_id:session.user.id,name:'Full Body A',exercises:next},{onConflict:'user_id,name'});setStatus(error?'Save failed':'Synced')};
 const editEx=(i,k,v)=>{const n=workout.map((x,j)=>j===i?{...x,[k]:v}:x);saveWorkout(n)}; const addEx=()=>saveWorkout([...workout,{id:Date.now(),name:'New exercise',prescription:'3 × 10',category:'CUSTOM',sets:[false,false,false],reps:[10,10,10]}]);
 const saveSkill=async(i,next)=>{const n=skills.map((x,j)=>j===i?next:x);setSkills(n);setStatus('Saving…');const {error}=await supabase.from('skill_progress').upsert({user_id:session.user.id,name:next.name,icon:next.icon,level:Number(next.level),progress:Number(next.progress),next_step:next.next,stages:next.stages,accent:next.accent},{onConflict:'user_id,name'});setStatus(error?'Save failed':'Synced')};
 const addMeasurement=async()=>{const prev=measurements.at(-1)||{};const row={user_id:session.user.id,measured_on:today(),weight_lb:prev.weight||null,waist_cm:prev.waist||null};const {data,error}=await supabase.from('measurements').upsert(row,{onConflict:'user_id,measured_on'}).select().single();if(!error)setMeasurements([...measurements.filter(x=>x.date!==today()),{id:data.id,date:data.measured_on,weight:data.weight_lb==null?'':Number(data.weight_lb),waist:data.waist_cm==null?'':Number(data.waist_cm)}].sort((a,b)=>a.date.localeCompare(b.date)))};
 const saveMeasurement=async(m)=>{setMeasurements(measurements.map(x=>x.id===m.id?m:x));await supabase.from('measurements').update({weight_lb:m.weight===''?null:Number(m.weight),waist_cm:m.waist===''?null:Number(m.waist)}).eq('id',m.id);setStatus('Synced')};
 const finish=async()=>{const done=workout.reduce((a,x)=>a+x.sets.filter(Boolean).length,0),total=workout.reduce((a,x)=>a+x.sets.length,0);const {data}=await supabase.from('workout_sessions').insert({user_id:session.user.id,session_date:today(),session_type:'Strength',completion:total?done/total:0,details:{workout}}).select().single();if(data)setHistory([...history,data]);};
 if(loading)return <div className="content"><main><p>Loading FORM…</p></main></div>;if(!session)return <Auth/>;return <div className="app"><aside className="sidebar"><div className="brand"><i>F</i><span>FORM<small>CLOUD SYNC</small></span></div><nav>{[['workout','Train',Dumbbell],['skills','Skills',Sparkles],['progress','Progress',Activity]].map(([id,l,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/><span>{l}</span></button>)}</nav><div className="privacy-badge"><ShieldCheck/><span>{status||'Private'}<small>{session.user.email}</small></span></div><button className="health-link" onClick={()=>supabase.auth.signOut()}><LogOut/><span>Sign out</span></button></aside><div className="content"><main><header className="topbar"><div><div className="eyebrow">PRIVATE · CROSS-DEVICE</div><h1>{tab==='workout'?'Workout editor':tab==='skills'?'Skill lab':'Measurements'}</h1></div><div className="avatar"><ShieldCheck size={20}/></div></header>
 {tab==='workout'&&<><div className="exercise-list">{workout.map((ex,i)=><article className="exercise card" key={ex.id}><div className="exercise-num">{String(i+1).padStart(2,'0')}</div><div className="exercise-main"><input value={ex.category} onChange={e=>editEx(i,'category',e.target.value)}/><h3><input value={ex.name} onChange={e=>editEx(i,'name',e.target.value)}/></h3><input value={ex.prescription} onChange={e=>editEx(i,'prescription',e.target.value)}/><div className="sets">{ex.sets.map((v,j)=><button className={v?'checked':''} key={j} onClick={()=>{const n=workout.map((x,k)=>k===i?{...x,sets:x.sets.map((s,q)=>q===j?!s:s)}:x);saveWorkout(n)}}><span>{v?<Check size={16}/>:j+1}</span><b>{ex.reps[j]}</b><small>REPS</small></button>)}</div></div><button className="close" onClick={()=>saveWorkout(workout.filter((_,j)=>j!==i))}><Trash2 size={18}/></button></article>)}</div><button className="primary" onClick={addEx}><Plus/> Add exercise</button> <button className="ghost" onClick={finish}><Save/> Log session</button></>}
 {tab==='skills'&&<section className="skill-grid">{skills.map((s,i)=><article className="skill-card card" key={s.name}><div className="skill-top"><div className="skill-glyph">{s.icon}</div><span>LEVEL <input type="number" min="0" value={s.level} onChange={e=>saveSkill(i,{...s,level:e.target.value})}/></span></div><h2>{s.name}</h2><label>Progress %<input type="number" min="0" max="100" value={s.progress} onChange={e=>saveSkill(i,{...s,progress:e.target.value})}/></label><label>Next step<input value={s.next} onChange={e=>saveSkill(i,{...s,next:e.target.value})}/></label><div className="bar"><i style={{width:`${s.progress}%`}}/></div></article>)}</section>}
 {tab==='progress'&&<><button className="primary" onClick={addMeasurement}><Plus/> Add today</button><section className="entries">{[...measurements].reverse().map(m=><div className="entry" key={m.id}><span>{m.date}</span><label><Scale size={14}/><input inputMode="decimal" value={m.weight} onChange={e=>saveMeasurement({...m,weight:e.target.value})}/> lb</label><label><Ruler size={14}/><input inputMode="decimal" value={m.waist} onChange={e=>saveMeasurement({...m,waist:e.target.value})}/> cm</label></div>)}</section></>}
 </main></div><nav className="bottom-nav">{[['workout','Train',Dumbbell],['skills','Skills',Sparkles],['progress','Progress',Activity]].map(([id,l,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/><span>{l}</span></button>)}</nav></div>}
createRoot(document.getElementById('root')).render(<App/>);
